# Generated by Django 5.1.7 on 2025-04-17 08:12

import PomoloBeeCore.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('yield_start_date', models.DateField()),
                ('yield_end_date', models.DateField()),
                ('yield_avg_kg', models.FloatField()),
                ('fruit_avg_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=50, null=True)),
                ('svg_map', models.FileField(blank=True, default='fields/svg/default_map.svg', help_text='Upload SVG map of the field layout.', null=True, upload_to=PomoloBeeCore.models.svg_upload_path)),
                ('background_image', models.ImageField(blank=True, help_text='Upload background image for the field layout.', null=True, upload_to=PomoloBeeCore.models.background_image_upload_path)),
                ('farm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='PomoloBeeCore.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('nb_plant', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='PomoloBeeCore.field')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='PomoloBeeCore.fruit')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('xy_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user_fruit_plant', models.FloatField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('default', 'Invalid status')], default='default', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PomoloBeeCore.row')),
            ],
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fruit_plant', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plant_kg', models.FloatField()),
                ('row_kg', models.FloatField()),
                ('maturation_grade', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('USR', 'User manual estimation'), ('MLI', 'Machine Learning (Image)'), ('MLV', 'Machine Learning (Video)')], default='MLI', max_length=3)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='PomoloBeeCore.image')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='PomoloBeeCore.row')),
            ],
        ),
        migrations.AddConstraint(
            model_name='row',
            constraint=models.UniqueConstraint(fields=('field', 'short_name'), name='unique_row_shortname_per_field'),
        ),
    ]
